### ISSUE TITLE
How to build, install or setup?

### ISSUE THREAD

**Issue by kutsan** [DrabWeb/macfeh#2]
It would be good to add documentations about installation steps for fellow non-Swift developers.

**Comment by axeII** [comment]
Open file macfeh.xcodeproj. Then you have to install needed libraries when prompted and after that open macfeh.xcodeproj (again). Find application settings under application (blue icon first in list on left side). Find signing label and sign application with your apple id. Then build it.
Path for builded applications is ```~/Library/Developer/Xcode/DerivedData/``` 

No app icon :(
And no idea what does open -b however I use open -a macfeh.app ~/path/to/img 

Edit:
Would be nice to close window via terminal.

**Comment by DrabWeb** [comment]
Sorry for the late response.

Should be as simple as opening `macfeh.xcodeproj` and pressing run. Can then cmd-click on the dock icon to show the application bundle in finder which you can copy to `/Applications/` or whatever. Code signing is not necessary at all either.

>No app icon

Doesn't have an icon yet.

>no idea what does open -b however I use open -a macfeh.app ~/path/to/img

The `-b` flag on `open` opens an application by bundle identifier, much better than specifying a full path to macfeh.

>Would be nice to close window via terminal.

Guess that would make sense, will work on it when I have time.

**Comment by axeII** [comment]
>Code signing is not necessary at all either.

Oh ok. Well last time I tried to build app from github I had to sign it. Sorry @kutsan.

**Comment by kutsan** [comment]
Thanks guys but I will be satisfied when you add these steps officially to `README.md`. So, everybody can read without thinking how.
